### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by webtrees-pesz** [reteP-riS/HistoricEvents-Germany#3]
Hallo Peter,

sorry, ich finde leider keine andere Möglichkeit zur Kontaktaufnahme. Kannst Du Dich bitte bei mir melden? Es geht um das deutschsprachige Handbuch zu webtrees.

Viele Grüße
Peter (Schulz)
pesz (at) gmx.de

**Comment by reteP-riS** [comment]
Wie besprochen.
